### ISSUE TITLE
Read - Integrating Classification and Association Rule Mining

### ISSUE THREAD

**Issue by maanvin** [OmkarMetri/Instacart-Market-Basket-Analysis#6]
Assignees please read this paper!

**Comment by maanvin** [comment]
[https://sci2s.ugr.es/keel/pdf/algorithm/congreso/1998-Liu-CBA.pdf](url)

**Comment by maanvin** [comment]
[Integrating Classification and Association Rule Mining.pdf](https://github.com/OmkarMetri/Instacart-Market-Basket-Analysis/files/2487940/Integrating.Classification.and.Association.Rule.Mining.pdf)

**Comment by OmkarMetri** [comment]
[Novel_approach.pdf](https://github.com/OmkarMetri/Instacart-Market-Basket-Analysis/files/2488322/Novel_approach.pdf)

Report Submitted.  Issue Closed.
