### ISSUE TITLE
Read - Association Rule Based Classification, A Thesis submitted to Worcester Polytechnic Institute

### ISSUE THREAD

**Issue by maanvin** [OmkarMetri/Instacart-Market-Basket-Analysis#7]
Assignees please read this paper!

**Comment by maanvin** [comment]
[Association Rule Based Classification.pdf](https://github.com/OmkarMetri/Instacart-Market-Basket-Analysis/files/2487979/Association.Rule.Based.Classification.pdf)

**Comment by OmkarMetri** [comment]
[Association.Rule.Based.Classification.pdf](https://github.com/OmkarMetri/Instacart-Market-Basket-Analysis/files/2488334/Association.Rule.Based.Classification.pdf)

Report Submitted through literature survey.
