### ISSUE TITLE
Read - An Efficient Approach to Mine Frequent Itemsets Using the Variant of Classic Apriori and FP-Tree

### ISSUE THREAD

**Issue by maanvin** [OmkarMetri/Instacart-Market-Basket-Analysis#8]
Assignees please read this paper!

**Comment by maanvin** [comment]
[An_Efficient_Approach_to_Mine_Frequent_I.pdf](https://github.com/OmkarMetri/Instacart-Market-Basket-Analysis/files/2487878/An_Efficient_Approach_to_Mine_Frequent_I.pdf)

**Comment by OmkarMetri** [comment]
[An_Efficient_Approach_to_Mine_Frequent_I.pdf](https://github.com/OmkarMetri/Instacart-Market-Basket-Analysis/files/2488310/An_Efficient_Approach_to_Mine_Frequent_I.pdf)

Report submitted through literature survey.
